name: testenv

on:
  push:
    branches: [ "main" ]   

jobs:
  build:

    runs-on: ubuntu-latest
    environment: developmentenv
    continue-on-error: false   
   
    container: 
      image: kirankumarsivapuram/base_image:3.0 
    steps:
    - uses: actions/checkout@v3
